"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Use environment variable `DJANGO_SECRET_KEY` in production. Fallback keeps
# current dev key for local convenience.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-=*@ohky+4vufd*m$fl$c--n)xfod^4xpik)dw8!l+vhswbw28g',
)

# SECURITY WARNING: don't run with debug turned on in production!
# Control via env var when deploying.
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

# Hosts allowed to serve the app. Can be overridden via env: DJANGO_ALLOWED_HOSTS
ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1,host.docker.internal').split(',')

# Configuracion de cabeceras para Reverse Proxy / Tunnels (Ngrok, Cloudflare, etc.)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True


# Application definition

INSTALLED_APPS = [
    'daphne',
    'channels',
    'polls.apps.PollsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',#para conectar con el frontend React
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'dj_rest_auth',
    'dj_rest_auth.registration',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # Debe estar antes de CommonMiddleware
    'django.middleware.common.CommonMiddleware',
    # DebugCSRFMiddleware (temporal) removido — usar solo en diagnóstico
    # 'polls.middleware.DebugCSRFMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'polls.middleware.AuditMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'
ASGI_APPLICATION = 'mysite.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}



# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'ic3_db',      # Nombre de la DB en Docker
        'USER': 'postgres',      # Usuario por defecto
        'PASSWORD': 'postgres',  # Contraseña definida en docker-compose
        'HOST': 'db',            # Nombre del servicio en tu archivo yaml
        'PORT': '5432',          # Puerto estándar de Postgres
    }
}

# Configuración para archivos de medios
MEDIA_URL = '/media/'  # Ruta para acceder a los archivos desde el navegador
MEDIA_ROOT = BASE_DIR / 'media'  # Ruta física donde se guardarán los archivos


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
# Directory where `collectstatic` will gather files
STATIC_ROOT = BASE_DIR / 'staticfiles'

# -----------------------------------------------------------------------------
# Email / SMTP configuration
# - By default use console email backend for development (prints emails to logs)
# - To use real SMTP configure the environment variables below.
# -----------------------------------------------------------------------------
DEFAULT_FROM_EMAIL = os.environ.get('DJANGO_DEFAULT_FROM', 'no-reply@localhost')
ACCOUNT_EMAIL_SUBJECT_PREFIX = "[Sistema SCADA IoT] "

# Frontend URL (used to build redirects in emails)
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:5173')

# Clave de registro (puede venir desde `key.env` o similar)
REGISTRATION_KEY = os.environ.get('REGISTRATION_KEY', None)

# Choose backend via env var. Default prints to console which is safe for dev.
EMAIL_BACKEND = os.environ.get('DJANGO_EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')

# SMTP settings (used when EMAIL_BACKEND is set to django.core.mail.backends.smtp.EmailBackend)
EMAIL_HOST = os.environ.get('DJANGO_EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('DJANGO_EMAIL_PORT', 587))
EMAIL_HOST_USER = os.environ.get('DJANGO_EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('DJANGO_EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('DJANGO_EMAIL_USE_TLS', 'True') == 'True'
EMAIL_USE_SSL = os.environ.get('DJANGO_EMAIL_USE_SSL', 'False') == 'True'

# When using console backend, emails are printed to stdout/logs. In production,
# set DJANGO_EMAIL_BACKEND to 'django.core.mail.backends.smtp.EmailBackend' and
# configure the host/user/password via env variables (do not store secrets in repo).

# Redirects y URLs usados por las plantillas y endpoints de registro/recupero.
ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = os.environ.get(
    'ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL', f"{FRONTEND_URL}/auth/verify-email"
)
ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = os.environ.get(
    'ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL', f"{FRONTEND_URL}/"
)
# URL base que usará el frontend para abrir la confirmación/reset (format strings
# pueden contener placeholders como {uid} y {token} según la implementación)
PASSWORD_RESET_CONFIRM_URL = os.environ.get(
    'PASSWORD_RESET_CONFIRM_URL', f"{FRONTEND_URL}/password-reset-confirm?uid={{uid}}&token={{token}}"
)

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field


# =============================================================================
# CONFIGURACIÓN DE DJANGO REST FRAMEWORK
# =============================================================================

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    # Cambiar permiso por defecto a `IsAuthenticated` protege toda la API
    # por defecto; marcar explícitamente `AllowAny` en vistas públicas.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DATETIME_FORMAT': '%Y-%m-%d %H:%M:%S',
    'DATE_FORMAT': '%Y-%m-%d',
}

# Usar manejador de excepciones personalizado para traducir mensajes al español
REST_FRAMEWORK['EXCEPTION_HANDLER'] = 'mysite.utils.exception_handler.custom_exception_handler'

# =============================================================================
# CONFIGURACIÓN DE CORS - Para permitir peticiones desde React frontend
# =============================================================================

# En desarrollo preferimos listar orígenes permitidos para permitir credenciales
# Evitar '*' cuando `CORS_ALLOW_CREDENTIALS = True` para no bloquear cookies.
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = [
    origin.strip() for origin in os.environ.get(
        'CORS_ALLOWED_ORIGINS', 'http://localhost:5173,http://127.0.0.1:5173'
    ).split(',') if origin.strip()
]
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*\.ngrok-free\.dev$",
    r"^https://.*\.ngrok-free\.app$",
    r"^https://.*\.ngrok\.io$",
]

# En producción, usar CORS_ALLOWED_ORIGINS específicas:
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:5173",  # Vite dev server
#     "http://127.0.0.1:5173",
#     "https://tu-dominio-produccion.com",
# ]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# django-allauth site id (can be overridden via env)
SITE_ID = int(os.environ.get('DJANGO_SITE_ID', 1))

# Orígenes confiables para peticiones CSRF desde el frontend (Vite dev server)
CSRF_TRUSTED_ORIGINS = os.environ.get(
    'DJANGO_CSRF_TRUSTED_ORIGINS',
    'http://localhost:5173,http://127.0.0.1:5173,http://localhost:8080,http://localhost:8081,http://127.0.0.1:8081'
).split(',')

# Ajustes de cookies CSRF/Session para desarrollo local (ajustar en producción)
def _env_samesite(var_name: str, default: str):
    v = os.environ.get(var_name, default)
    if v is None:
        return None
    if isinstance(v, str) and v.lower() in ['none', 'null', '']:
        return None
    return v

CSRF_COOKIE_SAMESITE = _env_samesite('CSRF_COOKIE_SAMESITE', 'Lax')
CSRF_COOKIE_SECURE = os.environ.get('CSRF_COOKIE_SECURE', 'False') == 'True'
SESSION_COOKIE_SAMESITE = _env_samesite('SESSION_COOKIE_SAMESITE', 'Lax')
SESSION_COOKIE_SECURE = os.environ.get('SESSION_COOKIE_SECURE', 'False') == 'True'

# Personalizar la vista de fallo CSRF para devolver mensajes en español
CSRF_FAILURE_VIEW = 'mysite.utils.csrf.csrf_failure'

# Authentication backends: include allauth
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

# allauth / registration settings
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_UNIQUE_EMAIL = True

# Use custom serializer for registration to enforce registration_key
REST_AUTH_REGISTER_SERIALIZER = 'polls.serializers.CustomRegisterSerializer'

REST_AUTH = {
    'USER_DETAILS_SERIALIZER': 'polls.serializers.UserSerializer',
}

# Usar adaptador personalizado para construir correctamente el enlace de
# confirmación (apunta al frontend SPA con ?key=...)
ACCOUNT_ADAPTER = 'polls.adapters.CustomAccountAdapter'



# =============================================================================
# CONFIGURACIÓN DE LOGGING - Sistema de logs del sistema
# =============================================================================

# Crear directorio logs si no existe
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'scada_system.log',
            'maxBytes': 10485760,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'scada_errors.log',
            'maxBytes': 10485760,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'mqtt_file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'mqtt_communication.log',
            'maxBytes': 5242880,  # 5MB
            'backupCount': 3,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['error_file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'scada': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'mqtt': {
            'handlers': ['console', 'mqtt_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}
# Asegurarse de no permitir '*' cuando se requieren credenciales
# (ya configurado arriba)
CORS_ALLOW_ALL_ORIGINS = False
# Para usar en el código:
# import logging
# logger = logging.getLogger('scada')
# logger.info('Mensaje informativo')
# logger.error('Mensaje de error')
# 
# logger_mqtt = logging.getLogger('mqtt')
# logger_mqtt.debug('Debug MQTT...')
