# Generated by Django 5.2.17 on 2026-09-07 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_sistema_diagrama_layout_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadalmacenamiento',
            name='seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_almacenamiento', to='polls.seccion'),
        ),
        migrations.AddField(
            model_name='unidadalmacenamiento',
            name='sistema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_almacenamiento', to='polls.sistema'),
        ),
    ]
