# Generated by Django 5.2.17 on 2026-09-07 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_unidadalmacenamiento_seccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapeoaccionmqtt',
            name='categoria_panel',
            field=models.CharField(default='Controles del Proceso', help_text='Sección o tarjeta contenedora', max_length=100),
        ),
        migrations.AddField(
            model_name='mapeoaccionmqtt',
            name='max_val',
            field=models.FloatField(blank=True, default=100.0, null=True),
        ),
        migrations.AddField(
            model_name='mapeoaccionmqtt',
            name='min_val',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='mapeoaccionmqtt',
            name='sistema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mapeos_acciones', to='polls.sistema'),
        ),
        migrations.AddField(
            model_name='mapeoaccionmqtt',
            name='tipo_control',
            field=models.CharField(choices=[('BOTON', 'Botón de Acción MQTT'), ('SLIDER', 'Barra Deslizante (Slider)'), ('NUMERICO', 'Campo Numérico (Input)'), ('RECETA', 'Panel de Receta (Manual / Plantilla)')], default='BOTON', max_length=30),
        ),
        migrations.AddField(
            model_name='mapeoaccionmqtt',
            name='unidad',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
