# Generated by Django 5.2.17 on 2026-09-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_mapeoaccionmqtt_categoria_panel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistema',
            name='tipo_sistema',
            field=models.CharField(choices=[('FLUIDOS', 'Fluidos / Líquidos'), ('SOLIDOS', 'Procesamiento de Sólidos'), ('EMPAQUE', 'Empaquetado y Envasado'), ('TEMPERATURA', 'Control de Temperatura'), ('GENERAL', 'Sistema General')], default='FLUIDOS', max_length=30),
        ),
    ]
