# Generated by Django 5.2.17 on 2026-09-08 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_sistema_tipo_sistema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapeoaccionmqtt',
            name='tipo_control',
            field=models.CharField(choices=[('BOTON', 'Botón de Acción MQTT'), ('SLIDER', 'Barra Deslizante (Slider)'), ('NUMERICO', 'Campo Numérico (Input)'), ('PARAMETRIZADO', 'Control Parametrizado (Campos Dinámicos)'), ('RECETA', 'Panel de Receta (Manual / Plantilla)')], default='BOTON', max_length=30),
        ),
    ]
