# Generated by Django 5.2.17 on 2026-09-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_alter_mapeoaccionmqtt_tipo_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivoscada',
            name='unidad_lectura',
            field=models.CharField(blank=True, default='N/A', help_text='Unidad de medida', max_length=20),
        ),
        migrations.AddField(
            model_name='dispositivoscada',
            name='valor_lectura',
            field=models.FloatField(blank=True, help_text='Último valor medido', null=True),
        ),
    ]
